


CREATE OR REPLACE DATABASE RHINO_MAGIC_SHOP_DB;

CREATE OR REPLACE SCHEMA RHINO_MAGIC_SHOP_DB.DATA_LOAD_SCHEMA;

USE RHINO_MAGIC_SHOP_DB;
CREATE OR REPLACE FILE FORMAT JSON_FILEFORMAT
TYPE = JSON
STRIP_OUTER_ARRAY = TRUE;

CREATE OR REPLACE STAGE RHINO_MAGIC_SHOP_DB.DATA_LOAD_SCHEMA.DATA_LOAD_STAGE
FILE_FORMAT=JSON_FILEFORMAT
COMMENT = 'FILE FORMAT FOR JSON FILES';


CREATE OR REPLACE SCHEMA RHINO_MAGIC_SHOP_DB.ORDERS_DATA;
CREATE OR REPLACE SCHEMA RHINO_MAGIC_SHOP_DB.CUSTOMERS_DATA;

CREATE OR REPLACE TABLE RHINO_MAGIC_SHOP_DB.CUSTOMERS_DATA.raw_customers_json(
    customers_json VARIANT 
);

CREATE OR REPLACE TABLE RHINO_MAGIC_SHOP_DB.ORDERS_DATA.raw_orders_json(
    orders_json VARIANT 
);

USE RHINO_MAGIC_SHOP_DB;
COPY INTO RHINO_MAGIC_SHOP_DB.CUSTOMERS_DATA.raw_customers_json
FROM @RHINO_MAGIC_SHOP_DB.DATA_LOAD_SCHEMA.DATA_LOAD_STAGE/customers_data.json
FILE_FORMAT = JSON_FILEFORMAT;

COPY INTO RHINO_MAGIC_SHOP_DB.ORDERS_DATA.raw_orders_json
FROM @RHINO_MAGIC_SHOP_DB.DATA_LOAD_SCHEMA.DATA_LOAD_STAGE/orders_data.json
FILE_FORMAT = JSON_FILEFORMAT;



CREATE OR REPLACE TABLE RHINO_MAGIC_SHOP_DB.CUSTOMERS_DATA.td_customers
AS
SELECT 
    customers_json['customer_id'] AS customer_id,
    customers_json['name'] AS name,
    customers_json['email'] AS email,
    customers_json['registration_date'] AS registration_date,
    customers_json['address'] AS address,
    customers_json['address']['street'] AS street,
    customers_json['address']['city'] AS city,
    customers_json['address']['zip_code'] AS zip_code,
    customers_json['loyalty_points'] AS loyalty_points
    
FROM RHINO_MAGIC_SHOP_DB.CUSTOMERS_DATA.raw_customers_json;

SELECT * FROM RHINO_MAGIC_SHOP_DB.CUSTOMERS_DATA.td_customers;
    

CREATE OR REPLACE TABLE RHINO_MAGIC_SHOP_DB.ORDERS_DATA.td_orders;

CREATE OR REPLACE TABLE RHINO_MAGIC_SHOP_DB.ORDERS_DATA.td_order_items;

